export const LOADING_VEHICULO = "LOADING_VEHICULO";
export const SAVE_LOADING_VEHICULO = "SAVE_LOADING_VEHICULO";
export const GET_VEHICULO = "GET_VEHICULO"
export const FORM_FAIL = "FORM_FAIL";
export const VEHICULO_FAIL = "VEHICULO_FAIL";