export const LOADING_COLABORADOR = "LOADING_COLABORADOR";
export const SAVE_LOADING_COLABORADOR = "SAVE_LOADING_COLABORADOR";
export const GET_COLABORADOR = "GET_COLABORADOR"
export const FORM_FAIL = "FORM_FAIL";
export const COLABORADOR_FAIL = "COLABORADOR_FAIL";