export const LOADING_REGISTRO = "LOADING_REGISTRO";
export const SAVE_LOADING_REGISTRO = "SAVE_LOADING_REGISTRO";
export const GET_REGISTRO = "GET_REGISTRO"
export const FORM_FAIL = "FORM_FAIL";
export const REGISTRO_FAIL = "REGISTRO_FAIL";